import scrollSuave from "./modules/scroll-suave.js";
import scrollAnimacao from "./modules/scroll-animacao.js";
import accordion from "./modules/accordion.js";
import tabNav from "./modules/tab-nav.js";
import modal from "./modules/modal.js";
import initTooltip from "./modules/tooltip.js";
import initDropdownMenu from "./modules/dropdown-menu.js";
import initMenuMobile from "./modules/menu-mobile.js";
import initFuncionamento from "./modules/funcionamento.js";
import initFetchAnimais from "./modules/fetch-animais.js";
import initFetchBitcoin from "./modules/fetch-bitcoin.js";

scrollSuave();
scrollAnimacao();
accordion();
tabNav();
modal();
initTooltip();
initDropdownMenu();
initMenuMobile();
initFuncionamento();
initFetchAnimais();
initFetchBitcoin();
